### ISSUE TITLE
NATS::Connect Error

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry-attic/tools-cf-plugin#6]
I Just installed this gem and I am getting a problem with nats.
Any idea?

```
|ruby-1.9.3-p448|→ cf dea-apps
Time of crash:
  2014-01-06 17:06:25 -0300

NATS::ConnectError: Could not connect to server on nats://nats:nats@127.0.0.1:4222

nats-0.4.28/lib/nats/client.rb:112:in `block in connect'
nats-0.4.28/lib/nats/client.rb:599:in `call'
nats-0.4.28/lib/nats/client.rb:599:in `process_disconnect'
nats-0.4.28/lib/nats/client.rb:589:in `unbind'
eventmachine-0.12.10/lib/eventmachine.rb:1417:in `event_callback'
eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
nats-0.4.28/lib/nats/client.rb:129:in `start'
tools-cf-plugin-3.0.0/lib/tools-cf-plugin/dea-apps.rb:37:in `render_apps'
tools-cf-plugin-3.0.0/lib/tools-cf-plugin/dea-apps.rb:29:in `dea_apps'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-5.2.2/lib/cf/cli.rb:195:in `block (2 levels) in execute'
cf-5.2.2/lib/cf/cli.rb:206:in `save_token_if_it_changes'
cf-5.2.2/lib/cf/cli.rb:194:in `block in execute'
cf-5.2.2/lib/cf/cli.rb:123:in `wrap_errors'
cf-5.2.2/lib/cf/cli.rb:190:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-5.2.2/bin/cf:18:in `<top (required)>'
ruby-1.9.3-p448/bin/cf:23:in `load'
ruby-1.9.3-p448/bin/cf:23:in `<main>'
ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by thansmann** [comment]
Hi @bonzofenix, 

It looks like the initial issue is that you did not give the 'tunnel-nats' argument. However, there may also be an issue running the tools as a stand-alone gem. The most reliable way to run it is:

```
git clone https://github.com/cloudfoundry/tools-cf-plugin
cd tools-cf-plugin/
bundle
ssh-add <bosh_ssh_keys>/<your id_rsa for director> # use your key for the director or microbosh
ssh vcap@<your bosh director> id # check connectivity 
bundle exec cf tunnel-nats <your bosh director> dea-apps --gateway vcap@<your bosh director> 
```

@thansmann && @dajulia3

**Comment by vito** [comment]
Try cf help dea-apps. You need to specify the credentials for the NATS server. See also tunnel-nats for connecting to a BOSH deployed NATS server.

**Comment by bonzofenix** [comment]
Thanks a lot now I could connect to it but I am getting the following error:

```
open failed: administratively prohibited: open failed
```

This is the full stack:

```
±  |master ✗| → bundle exec cf tunnel-nats 54.204.5.198 dea-apps
Authenticating as admin... OK
Director: https://54.204.5.198:25555
Getting deployments... OK
1: bosh
2: cloudfoundry
Which deployment?> 2

Downloading cloudfoundry manifest... OK
Opening local tunnel to NATS... OK
Logging in as admin user.  channel 2: open failed: administratively prohibited: open failed
... OK
NATS connection: nats://nats:5fb77407c872@127.0.0.1:58968
channel 2: open failed: administratively prohibited: open failed
```

**Comment by thansmann** [comment]
@bonzofenix, looks like your missing an argument to cf, try:

``` bash
bundle exec cf tunnel-nats 54.204.5.198 dea-apps --gateway vcap@54.204.5.198
```

@thansmann && @dajulia3

**Comment by thansmann** [comment]
@bonzofenix - we're going to close this as a misconfig. If you need any more help please join the [Cloudfoundry-Dev  mailing list](https://groups.google.com/a/cloudfoundry.org/forum/#!forum/vcap-user) and ask there. 

@thansmann && @dajulia3 - Community Pair
